### ISSUE TITLE
Work Status and Assignments

### ISSUE THREAD

**Issue by CloudiDust** [CloudiDust/wesnoth-cn#1]
This issue is for tracking who is translating what.

**release-notes-1.12**: [Finished].
**wesnoth**: [Finished].
**wesnoth-ai**: _[Pending Assignment]_.
**wesnoth-anl**: [Finished].
**wesnoth-aoi**: [Finished].
**wesnoth-did**: [Finished].
**wesnoth-dm**: [Finished].
**wesnoth-dw**: [Finished].
**wesnoth-editor**: [Finished].
**wesnoth-ei**: [Finished].
**wesnoth-help**: [Finished].
**wesnoth-httt**: [Finished].
**wesnoth-l**: [Finished].
**wesnoth-lib**: [Finished].
**wesnoth-low**: [Finished].
**wesnoth-manpages**: [Finished].
**wesnoth-manual**: [Finished].
**wesnoth-multiplayer**: [Finished].
**wesnoth-nr**: [Finished].
**wesnoth-sof**: [Finished].
**wesnoth-sotbe**: [Finished].
**wesnoth-tb**: [Finished].
**wesnoth-test**: [Finished].
**wesnoth-thot**: [Finished].
**wesnoth-trow**: [Finished].
**wesnoth-tsg**: [Finished].
**wesnoth-tutorial**: [Finished].
**wesnoth-units**:  [Finished].
**wesnoth-utbs**: BrianLee.

**Comment by qijunumich** [comment]
Hi, I want to help the translation. Is the list means that only wesnoth-ei and wesnoth-utbs are still needed for translation?

**Comment by CloudiDust** [comment]
@qijunumich currently `ei`, `utbs` and `sotbe` need tranlation and Axalara is working on `sotbe`.

We have a QQ group for discussion. 131160118. Welcome. :)

**Comment by CloudiDust** [comment]
Now I am translating `wesnoth-ei`, and `wesnoth-utbs` is open for assignment.

**Comment by CloudiDust** [comment]
The translation for `wesnoth-ei` is finished.

**Comment by brianlee2014** [comment]
所以的翻译项目已经结束了？

**Comment by CloudiDust** [comment]
@brianlee2014 新加了之前漏掉的ai，另外utbs也还有部分未翻译。

**Comment by brianlee2014** [comment]
好的，这部分我拿下了。

**Comment by vinneymail** [comment]
@CloudiDust 申请哈里发派系翻译修正。

**Comment by CloudiDust** [comment]
@vinneymail, 已合并。

**Comment by CloudiDust** [comment]
The translations are now finished for 1.14 RC1 (1.13.12), so I am closing this issue.
