### ISSUE TITLE
古人之密部分错别字，修改了一些认为不是很通顺的地方

### ISSUE THREAD

**Issue by termanary** [CloudiDust/wesnoth-cn#11]
原谅我并不是很会用github的功能
我修改了po，可是我应该如何提交呢

**Comment by qrqiuren** [comment]
学习使用GitHub，或者可以直接联系@CloudiDust

**Comment by termanary** [comment]
加那个q群有用吗，我试了下，我没进

**Comment by CloudiDust** [comment]
@termanary 谢谢翻译，抱歉之前一段时间没上github。Orz
