### ISSUE TITLE
韦诺之战F1帮助“武器特性”下面的页面无法浏览

### ISSUE THREAD

**Issue by arzyu** [CloudiDust/wesnoth-cn#12]
Steam 版本
简体中文时，点击武器特性子项会退出到游戏主界面，切换到英文界面无此问题。

**Comment by CloudiDust** [comment]
您好，我用steam上最新的版本（1.14.13）测试了一下，确实武器特性子项有问题，目前的bug现象是帮助窗口会消失。看了下翻译文件，暂时还未发现问题在哪里，会继续研究的。

**Comment by CloudiDust** [comment]
发现是翻译文本的标记里面，有处应该用半角单引号，实际用了全角单引号，现在已经改过来了。顺便修了另外几个bug。谢谢！
