### ISSUE TITLE
sync with upstream

### ISSUE THREAD

**Issue by celerini** [CloudiDust/wesnoth-cn#16]
Hi,

I would like to fix parsing errors in wesnoth-help/zh_CN.po, but it is older than upstream.

Should I do msgmerge on my own to get latest changes, or do you have some other workflow?

**Comment by CloudiDust** [comment]
Hi,
I have merged the upstream changes into this repo.

**Comment by celerini** [comment]
Thanks for merging. The help still differs (missing #: and #| comments), but I don't consider it as a problem.

I only wanted to make fixes which don't add an extra work for you.

**Comment by CloudiDust** [comment]
Thanks. I chose to strip those two kinds of comments when syncing, so they went missing.
I'll close this issue now.
